spring:
  datasource:
    url: jdbc:mysql://database-1.cttuoh0xl2hh.ap-northeast-2.rds.amazonaws.com:3306/MyDB?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username : root
    password : password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
